import 'package:equatable/equatable.dart';

import 'enums/print_enums.dart';

/// Represents the configuration settings for a specific printer.
///
/// This is a pure domain entity with no framework dependencies.
/// Maps to the `printer_configs` table in the database.
class PrinterConfig extends Equatable {
  /// Unique identifier. Null when creating a new config (auto-generated by DB).
  final int? id;

  /// The printer this config belongs to. Foreign key to `printers.id`.
  final int printerId;

  /// The selected paper size.
  final PaperSize paperSize;

  /// The type of paper media loaded.
  final PaperType paperType;

  /// Print orientation (portrait or landscape).
  final Orientation orientation;

  /// Top margin in millimeters.
  final double marginTop;

  /// Left margin in millimeters.
  final double marginLeft;

  /// Right margin in millimeters.
  final double marginRight;

  /// Print darkness/density level (1-15, default 8).
  final int printDarkness;

  /// Print speed in inches per second (default 4.0).
  final double printSpeed;

  /// How content is scaled to fit the print area.
  final ScalingMode scalingMode;

  /// Scaling percentage value (50-200, default 100).
  final int scalingValue;

  /// Custom paper width in mm. Used when [paperSize] is [PaperSize.custom].
  final int? customWidthMm;

  /// Custom paper height in mm. Used when [paperSize] is [PaperSize.custom].
  final int? customHeightMm;

  /// Gap between labels in mm. Used when [paperType] is [PaperType.label].
  final double labelGap;

  const PrinterConfig({
    this.id,
    required this.printerId,
    this.paperSize = PaperSize.A6,
    this.paperType = PaperType.label,
    this.orientation = Orientation.portrait,
    this.marginTop = 0.0,
    this.marginLeft = 0.0,
    this.marginRight = 0.0,
    this.printDarkness = 8,
    this.printSpeed = 4.0,
    this.scalingMode = ScalingMode.fitWidth,
    this.scalingValue = 100,
    this.customWidthMm,
    this.customHeightMm,
    this.labelGap = 0.0,
  });

  /// The effective width in mm, considering custom paper size.
  int get effectiveWidthMm =>
      paperSize == PaperSize.custom ? (customWidthMm ?? 0) : paperSize.widthMm;

  /// The effective height in mm, considering custom paper size.
  int get effectiveHeightMm =>
      paperSize == PaperSize.custom
          ? (customHeightMm ?? 0)
          : paperSize.heightMm;

  /// Creates a copy of this [PrinterConfig] with the given fields replaced.
  PrinterConfig copyWith({
    int? id,
    int? printerId,
    PaperSize? paperSize,
    PaperType? paperType,
    Orientation? orientation,
    double? marginTop,
    double? marginLeft,
    double? marginRight,
    int? printDarkness,
    double? printSpeed,
    ScalingMode? scalingMode,
    int? scalingValue,
    int? customWidthMm,
    int? customHeightMm,
    double? labelGap,
  }) {
    return PrinterConfig(
      id: id ?? this.id,
      printerId: printerId ?? this.printerId,
      paperSize: paperSize ?? this.paperSize,
      paperType: paperType ?? this.paperType,
      orientation: orientation ?? this.orientation,
      marginTop: marginTop ?? this.marginTop,
      marginLeft: marginLeft ?? this.marginLeft,
      marginRight: marginRight ?? this.marginRight,
      printDarkness: printDarkness ?? this.printDarkness,
      printSpeed: printSpeed ?? this.printSpeed,
      scalingMode: scalingMode ?? this.scalingMode,
      scalingValue: scalingValue ?? this.scalingValue,
      customWidthMm: customWidthMm ?? this.customWidthMm,
      customHeightMm: customHeightMm ?? this.customHeightMm,
      labelGap: labelGap ?? this.labelGap,
    );
  }

  @override
  List<Object?> get props => [
        id,
        printerId,
        paperSize,
        paperType,
        orientation,
        marginTop,
        marginLeft,
        marginRight,
        printDarkness,
        printSpeed,
        scalingMode,
        scalingValue,
        customWidthMm,
        customHeightMm,
        labelGap,
      ];
}
