import 'package:equatable/equatable.dart';

import 'enums/print_enums.dart';

/// Represents a print job submitted to a printer.
///
/// This is a pure domain entity with no framework dependencies.
/// Maps to the `print_jobs` table in the database.
class PrintJob extends Equatable {
  /// Unique identifier. Null when creating a new job (auto-generated by DB).
  final int? id;

  /// The printer this job is assigned to. Foreign key to `printers.id`.
  final int printerId;

  /// User-visible name for the job (e.g., "Invoice #1234").
  final String jobName;

  /// The type of document being printed.
  final DocumentType documentType;

  /// Total number of pages in the document.
  final int totalPages;

  /// Number of copies to print.
  final int copies;

  /// Current status of the print job.
  final JobStatus status;

  /// Timestamp when the job was created.
  final DateTime? createdAt;

  const PrintJob({
    this.id,
    required this.printerId,
    required this.jobName,
    required this.documentType,
    this.totalPages = 1,
    this.copies = 1,
    this.status = JobStatus.pending,
    this.createdAt,
  });

  /// Creates a copy of this [PrintJob] with the given fields replaced.
  PrintJob copyWith({
    int? id,
    int? printerId,
    String? jobName,
    DocumentType? documentType,
    int? totalPages,
    int? copies,
    JobStatus? status,
    DateTime? createdAt,
  }) {
    return PrintJob(
      id: id ?? this.id,
      printerId: printerId ?? this.printerId,
      jobName: jobName ?? this.jobName,
      documentType: documentType ?? this.documentType,
      totalPages: totalPages ?? this.totalPages,
      copies: copies ?? this.copies,
      status: status ?? this.status,
      createdAt: createdAt ?? this.createdAt,
    );
  }

  @override
  List<Object?> get props => [
        id,
        printerId,
        jobName,
        documentType,
        totalPages,
        copies,
        status,
        createdAt,
      ];
}
