import 'package:equatable/equatable.dart';

import 'enums/printer_enums.dart';

/// Represents a physical printer device in the system.
///
/// This is a pure domain entity with no framework dependencies.
/// Maps to the `printers` table in the database.
class Printer extends Equatable {
  /// Unique identifier. Null when creating a new printer (auto-generated by DB).
  final int? id;

  /// User-defined name for the printer.
  final String name;

  /// Whether this is a label or receipt printer.
  final PrinterType type;

  /// The communication protocol (TSPL or ESC/POS).
  final PrinterProtocol protocol;

  /// How the app connects to the printer (Bluetooth or Wi-Fi).
  final ConnectionMethod connectionMethod;

  /// Bluetooth MAC address. Required when [connectionMethod] is [ConnectionMethod.bluetooth].
  final String? btMacAddress;

  /// Wi-Fi IP address. Required when [connectionMethod] is [ConnectionMethod.wifi].
  final String? wifiIp;

  /// Wi-Fi port number. Defaults to 9100 (standard raw printing port).
  final int wifiPort;

  /// Whether this printer is the default printer.
  final bool isDefault;

  /// Timestamp when the printer was registered.
  final DateTime? createdAt;

  const Printer({
    this.id,
    required this.name,
    required this.type,
    required this.protocol,
    required this.connectionMethod,
    this.btMacAddress,
    this.wifiIp,
    this.wifiPort = 9100,
    this.isDefault = false,
    this.createdAt,
  });

  /// Creates a copy of this [Printer] with the given fields replaced.
  Printer copyWith({
    int? id,
    String? name,
    PrinterType? type,
    PrinterProtocol? protocol,
    ConnectionMethod? connectionMethod,
    String? btMacAddress,
    String? wifiIp,
    int? wifiPort,
    bool? isDefault,
    DateTime? createdAt,
  }) {
    return Printer(
      id: id ?? this.id,
      name: name ?? this.name,
      type: type ?? this.type,
      protocol: protocol ?? this.protocol,
      connectionMethod: connectionMethod ?? this.connectionMethod,
      btMacAddress: btMacAddress ?? this.btMacAddress,
      wifiIp: wifiIp ?? this.wifiIp,
      wifiPort: wifiPort ?? this.wifiPort,
      isDefault: isDefault ?? this.isDefault,
      createdAt: createdAt ?? this.createdAt,
    );
  }

  @override
  List<Object?> get props => [
        id,
        name,
        type,
        protocol,
        connectionMethod,
        btMacAddress,
        wifiIp,
        wifiPort,
        isDefault,
        createdAt,
      ];
}
