import 'package:equatable/equatable.dart';

import 'printer_config.dart';

/// Represents a reusable print template with layout dimensions.
///
/// This is a pure domain entity with no framework dependencies.
/// Maps to the `templates` table in the database.
class Template extends Equatable {
  /// Unique identifier. Null when creating a new template (auto-generated by DB).
  final int? id;

  /// User-defined name for the template.
  final String name;

  /// Template width in millimeters.
  final int widthMm;

  /// Template height in millimeters.
  final int heightMm;

  /// Timestamp when the template was created.
  final DateTime? createdAt;

  /// Timestamp when the template was last updated.
  final DateTime? updatedAt;

  /// Associated printer configuration, if any.
  ///
  /// This is loaded via the `config_id` foreign key in the `templates` table.
  final PrinterConfig? config;

  const Template({
    this.id,
    required this.name,
    required this.widthMm,
    required this.heightMm,
    this.createdAt,
    this.updatedAt,
    this.config,
  });

  /// Creates a copy of this [Template] with the given fields replaced.
  Template copyWith({
    int? id,
    String? name,
    int? widthMm,
    int? heightMm,
    DateTime? createdAt,
    DateTime? updatedAt,
    PrinterConfig? config,
  }) {
    return Template(
      id: id ?? this.id,
      name: name ?? this.name,
      widthMm: widthMm ?? this.widthMm,
      heightMm: heightMm ?? this.heightMm,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      config: config ?? this.config,
    );
  }

  @override
  List<Object?> get props => [
        id,
        name,
        widthMm,
        heightMm,
        createdAt,
        updatedAt,
        config,
      ];
}
